### ISSUE TITLE
Error when using API with Java 17

### ISSUE THREAD

**Issue by JoshBargar** [Wisser/Jailer#103]
When running a Spring Boot 3.x application with Java 17, upon startup this error is received:

```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-03-10T13:34:37.423-05:00 ERROR 27984 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at net.sf.jailer.configuration.Configuration.loadConfigurationFile(Configuration.java:245) ~[jailer-engine-14.3.jar:na]
	at net.sf.jailer.configuration.Configuration.getInstance(Configuration.java:212) ~[jailer-engine-14.3.jar:na]
	at net.sf.jailer.configuration.DBMS.values(DBMS.java:64) ~[jailer-engine-14.3.jar:na]
	at net.sf.jailer.configuration.Configuration.<clinit>(Configuration.java:344) ~[jailer-engine-14.3.jar:na]
	at net.sf.jailer.configuration.DBMS.forDBMS(DBMS.java:150) ~[jailer-engine-14.3.jar:na]
	at net.sf.jailer.configuration.DBMS.<clinit>(DBMS.java:171) ~[jailer-engine-14.3.jar:na]
```

This is the code causing the exception:

```java
DataSource dataSource = getDataSource(); // ComboPooledDataSource
Subsetter subsetter = new Subsetter(
	dataSource,
	DBMS.MySQL,
	dataModelDirectoryPath.toUri().toURL(),
	extractionModelFilePath.toUri().toURL(),
	ScriptFormat.SQL
);
```

Is there a way to use this API with Jakarta?

**Comment by Wisser** [comment]
You need the JAXB jars. Either you add the files 
to the classpath (contained in the jailer-n.zip):

```
lib/jaxb-api-2.3.0-b170201.1204.jar
lib/jaxb-core-2.3.0-b170127.1453.jar
lib/jaxb-impl-2.3.0-b170127.1453.jar
```

or add the dependencies:

```
<dependencies>
    <dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-impl</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>javax.activation</groupId>
        <artifactId>activation</artifactId>
        <version>1.1.1</version>
    </dependency>
</dependencies>

```
If you use maven or similar.

See
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception
