### ISSUE TITLE
ClickHouse database support

### ISSUE THREAD

**Issue by Slach** [Wisser/Jailer#110]
Thanks for your nice tool.

Would you like to add support for ClickHouse database?
https://clickhouse.com/docs/en/intro

**Comment by Wisser** [comment]
The recently published release 15.8.4 now also offers support for the ClickHouse DBMS, as far as this is possible.
Since foreign keys are not supported and there is no comparable concept (correct me if I'm wrong), associations have to be entered manually.
If there are any problems with this, please let me know.

**Comment by Slach** [comment]
@Wisser checked, works like a charm, thank you so much for your efforts
![image](https://github.com/Wisser/Jailer/assets/105560/3c5a8383-eb4a-49de-b6ad-73ed366d359a)
only one thing
during download driver https://github.com/ClickHouse/clickhouse-java/releases/download/v0.6.0-patch2/clickhouse-jdbc-0.6.0-patch2-all.jar 

return 
```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:202)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at net.sf.jailer.ui.util.HttpDownload.get(HttpDownload.java:80)
	at net.sf.jailer.ui.util.HttpDownload.get(HttpDownload.java:42)
	at net.sf.jailer.ui.DbConnectionDetailsEditor$40.lambda$run$2(DbConnectionDetailsEditor.java:1944)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.sf.jailer.ui.DbConnectionDetailsEditor$40.run(DbConnectionDetailsEditor.java:1937)
	
	
	at net.sf.jailer.ui.util.ConcurrentTaskControl$5.run(ConcurrentTaskControl.java:221)
	at net.sf.jailer.ui.util.ConcurrentTaskControl$3.run(ConcurrentTaskControl.java:153)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

looks weird, maybe my 
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-58)
OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)

doing something wrong in my sandbox

**Comment by Wisser** [comment]
Thanks for the feedback!

About the download problem: could you please test if the problem also occurs when you download the "jailer_15.8.4.zip" file from github and start Jailer from here? (If you have not already done this).

The background is that the installation artifacts (*.msi and *.deb) use their own JVM (currently version 15.0), not the locally installed one.

You can find which version of the JVM Jailer is using via the menu item "Help" -> "About Jailer".

![image](https://github.com/Wisser/Jailer/assets/861721/005d810a-101e-4a8d-a7a9-1fbca6c9b401)
![image](https://github.com/Wisser/Jailer/assets/861721/0ed04204-a55c-4230-8715-319421c0474a)
