### ISSUE TITLE
NPE when using Weblogic Datasource

### ISSUE THREAD

**Issue by didos36** [Wisser/Jailer#4]
Hello, 

When creating Subsetter like that:

`@Resource(name = "jdbc/datasrouce")
    DataSource dataSource;

      @PostConstruct
    public void init() throws IOException {
        subsetter = new Subsetter(dataSource,
            DBMS.ORACLE,
            RestControler.class.getResource("model"),
            RestControler.class.getResource("extraction-model.csv"),
            ScriptFormat.SQL);`

and executing using _execute_ method, I'm getting NPE here:
 `java.lang.NullPointerException
	at net.sf.jailer.util.Quoting.<init>(Quoting.java:90)
	at net.sf.jailer.entitygraph.remote.RemoteEntityGraph.<init>(RemoteEntityGraph.java:83)
	at net.sf.jailer.entitygraph.remote.RemoteEntityGraph.create(RemoteEntityGraph.java:120)
	at net.sf.jailer.subsetting.SubsettingEngine.export(SubsettingEngine.java:1303)
	at net.sf.jailer.api.Subsetter.execute(Subsetter.java:150)
	at net.sf.jailer.api.Subsetter.execute(Subsetter.java:118)`

` if(session.dbUrl.toLowerCase().startsWith("jdbc:jtds:")) `

In my case _session.dbUrl_ is null.

I think this is comming from Session class where 
`   this.dbUrl = dataSource instanceof BasicDataSource?((BasicDataSource)dataSource).dbUrl:null;`

**Comment by Wisser** [comment]
Hi,
I've fixed this issue and released version 7.3
